export const LIST_IDEAS = 'LIST_IDEAS';
export const UPSERT_IDEA = 'UPSERT_IDEA';
export const REMOVE_IDEA = 'REMOVE_IDEA';

export const SET_IDEA_SORT_TYPE = 'SET_IDEA_SORT_TYPE';
export const SET_IDEA_SORT_DESCENDING = 'SET_IDEA_SORT_DESCENDING';
